version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.18.1

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: |
            NPMTAG=$(npm run fetch:npm_tag --silent)
            npm publish --tag $NPMTAG

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/