version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test ci flow
          command: echo "testing circle ci"
      # - run:
      #     name: Authenticate with registry
      #     command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      # - run:
      #     name: Publish package
      #     command: npm publish

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: feature/api-1540_npm_ci_publish
              # ignore: /.*/