version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16.10.0

commands:
  generate_github_pr_for_docs:
    parameters:
      checkout:
        default: true
        description: Boolean value used for whether or not to checkout bitbucket repo as a first step. Default is true.
        type: boolean
    steps:
      - add_ssh_keys
      - when:
          condition: <<parameters.checkout>>
          steps:
            - checkout
      - run:
          name: Docs PR Generating
          command: |
            . ./.sentiance/doc-pr-gen.sh

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run tsc
      - run: npm run test
  android_test:
    docker:
      - image: cimg/android:2024.01.1-node
    environment:
      BUNDLE_PATH: vendor/bundle
      _JAVA_OPTIONS: -Xmx3g
    steps:
      - checkout
      - run: java -version
      - run: npm install
      - run: npm run androidTest
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Sync package versions for all modules
          command: npm run sync:package_versions
      - run:
          name: Compile Typescript code
          command: npm run tsc
      - run:
          name: Tag and publish all subpackages
          command: |
            NPMTAG=$(npm run fetch:npm_tag --silent)
            npm publish --workspaces --tag $NPMTAG
  publish_docs:
    environment:
      DOCKER_BUILDKIT: "1"
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - generate_github_pr_for_docs

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - android_test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires: [test, android_test]
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish_docs:
          context: default
          requires: [test, android_test]
          filters:
            branches:
              only:
                - main
