version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16.10.0

commands:
  publish-all-packages:
    description: "A command that tags and publishes all subpackages"
    steps:
      - run:
          command: |
            NPMTAG=$(npm run fetch:npm_tag --silent)
            npm publish --workspaces --tag $NPMTAG

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          publish-all-packages:

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires: [ test ]
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
